# Default values for gitlab-tuning.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rabbitmqUrl: "amqp://guest:guest@rabbitmq:5672"
redisUrl: ""
server:
  enable: true
  token: "your-secret-token"
  replicaCount: 2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 36Mi
periodiq:
  enable: true
  resources:
    requests:
      cpu: 50m
      memory: 36Mi
dramatiq:
  enable: true
  gitlabToken: "your-secret-token"
  statisticUrl: "http://statistic.com/post-receive"
  ldapUrl: 'ldap://company.com_by:12345'
  ldapUser: 'Reader@company.com_by'
  ldapPass: 'password'
  ldapBase: 'DC=company,DC=com_by'
  sync_avatars: '0 0 * * *'
  environments:
  replicaCount: 2
  hpa:
    averageUtilization: 75
    minReplicas: 2
    maxReplicas: 10
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 64Mi
env:
  GITLAB_URL: http://gitlab-unicorn.gitlab:8080
  LDAP_OBJECTCLASS_GROUP: group
  LDAP_OBJECTCLASS_USER: user
image:
  repository: negash/gitlab-tuning
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
  # clusterIP: 10.x.x.x
nodeSelector: {}
tolerations: []
affinity: {}

nameOverride: ""
fullnameOverride: ""
