{{- if .Values.cron.enable }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "gitlab-tuning.fullname" . }}-cron
  labels:
    app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
    helm.sh/chart: {{ include "gitlab-tuning.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: cron
spec:
  schedule: {{ .Values.cron.enable }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-cron
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
            - python3
            - -u
            - cron.py
          restartPolicy: OnFailure
          envFrom:
          - secretRef:
              name: {{ include "gitlab-tuning.fullname" . }}
              optional: false
          env:
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.cron.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
