apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-tuning.fullname" . }}-dramatiq
  labels:
    app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
    helm.sh/chart: {{ include "gitlab-tuning.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: dramatiq
spec:
  replicas: {{ .Values.dramatiq.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: dramatiq
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9191"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: dramatiq
    spec:
      volumes:
        - emptyDir:
            sizeLimit: 128Mi
          name: prometheus
      containers:
        - name: {{ .Chart.Name }}-dramatiq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['dramatiq-gevent']
          args:  ['tasks', '-p', '4', '-t', '100']
          volumeMounts:
            - name: prometheus
              mountPath: /tmp/dramatiq-prometheus
          env:
            - name: STATISTIC_URL
              valueFrom:
                secretKeyRef:
                  key: STATISTIC_URL
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: GITLAB_TOKEN
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_URL
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            - name: LDAP_URL
              valueFrom:
                secretKeyRef:
                  key: LDAP_URL
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            - name: LDAP_USER
              valueFrom:
                secretKeyRef:
                  key: LDAP_USER
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            - name: LDAP_PASS
              valueFrom:
                secretKeyRef:
                  key: LDAP_PASS
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            - name: LDAP_BASE
              valueFrom:
                secretKeyRef:
                  key: LDAP_BASE
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: prometheus
              containerPort: 9191
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: prometheus
          readinessProbe:
            httpGet:
              path: /
              port: prometheus
          resources:
            {{- toYaml .Values.dramatiq.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
