{{- if .Values.dramatiq.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-tuning.fullname" . }}-dramatiq
  labels:
    app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
    helm.sh/chart: {{ include "gitlab-tuning.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: dramatiq
spec:
  replicas: {{ .Values.dramatiq.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: dramatiq
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9191"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: dramatiq
    spec:
      volumes:
        - emptyDir:
            sizeLimit: 128Mi
          name: prometheus
      containers:
        - name: {{ .Chart.Name }}-dramatiq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['dramatiq']
          args:  ['tasks']
          volumeMounts:
            - name: prometheus
              mountPath: /tmp/dramatiq-prometheus
          envFrom:
          - secretRef:
              name: {{ include "gitlab-tuning.fullname" . }}
              optional: false
          env:
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http-prometheus
              containerPort: 9191
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: prometheus
          readinessProbe:
            httpGet:
              path: /
              port: prometheus
          resources:
            {{- toYaml .Values.dramatiq.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
