apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "gitlab-tuning.fullname" . }}-dramatiq
    labels:
        app: dramatiq
        app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
spec:
    maxReplicas: {{ .Values.dramatiq.hpa.maxReplicas }}
    minReplicas: {{ .Values.dramatiq.hpa.minReplicas }}
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: {{ include "gitlab-tuning.fullname" . }}-dramatiq
    targetCPUUtilizationPercentage: 80