apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-tuning.fullname" . }}-periodiq
  labels:
    app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
    helm.sh/chart: {{ include "gitlab-tuning.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: periodiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: periodiq
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9191"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: periodiq
    spec:
      volumes:
        - emptyDir:
            sizeLimit: 128Mi
          name: prometheus
      containers:
        - name: {{ .Chart.Name }}-periodiq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['periodiq']
          args:  ['tasks']
          volumeMounts:
            - name: prometheus
              mountPath: /tmp/periodiq-prometheus
          env:
            {{- if .Values.rabbitmqUrl -}}
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_URL
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            {{- else -}}
            {{- if .Values.redisUrl -}}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: REDIS_URL
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            {{- else -}}
            - name: CRON_SYNC_AVATARS
              valueFrom:
                secretKeyRef:
                  key: CRON_SYNC_AVATARS
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http-prometheus
              containerPort: 9191
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: prometheus
          readinessProbe:
            httpGet:
              path: /
              port: prometheus
          resources:
            {{- toYaml .Values.periodiq.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
