apiVersion: v1
kind: Secret
metadata:
    name: {{ include "gitlab-tuning.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
        helm.sh/chart: {{ include "gitlab-tuning.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
    REDIS_URL: {{ required "A valid .Values.redisUrl entry is required!" .Values.redisUrl | b64enc | quote }}
    TOKEN: {{ required "A valid .Values.server.Token entry is required!" .Values.server.token | b64enc | quote }}
    GITLAB_TOKEN: {{ required "A valid .Values.dramatiq.gitlabToken entry is required!" .Values.dramatiq.gitlabToken | b64enc | quote }}
    STATISTIC_URL: {{ required "A valid .Values.dramatiq.statisticUrl entry is required!" .Values.dramatiq.statisticUrl | b64enc | quote }}
    LDAP_URL: {{ required "A valid .Values.dramatiq.ldapUrl entry is required!" .Values.dramatiq.ldapUrl | b64enc | quote }}
    LDAP_USER: {{ required "A valid .Values.dramatiq.ldapUser entry is required!" .Values.dramatiq.ldapUser | b64enc | quote }}
    LDAP_PASS: {{ required "A valid .Values.dramatiq.ldapPass entry is required!" .Values.dramatiq.ldapPass | b64enc | quote }}
    LDAP_BASE: {{ required "A valid .Values.dramatiq.ldapBase entry is required!" .Values.dramatiq.ldapBase | b64enc | quote }}