apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-tuning.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
    helm.sh/chart: {{ include "gitlab-tuning.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gitlab-tuning.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: server
    spec:
      volumes:
        - name: service
          secret:
            secretName: {{ include "gitlab-tuning.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['python3']
          args:  ['-um', 'japronto', 'run:app']
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: REDIS_URL
                  name: {{ include "gitlab-tuning.fullname" . }}
                  optional: false
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
