version: '2'
services:
  rabbitmq:
    image: rabbitmq:alpine
  dramatiq:
    links:
      - rabbitmq
    build:
      context: .
    env_file:
      - .env
    volumes:
      - /tmp/dramatiq-prometheus
    command: ["dramatiq", "tasks"]
    ports:
      - 9191:9191
  server:
    links:
      - rabbitmq
    build:
      context: .
    command: ["python3", "-um", "japronto", "run:app"]
    ports:
      - 8080:8080