version: '2'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
  dramatiq:
    links:
      - rabbitmq
    build:
      context: .
    env_file:
      - .env
    volumes:
      - /tmp/dramatiq-prometheus
    command: ["dramatiq", "tasks"]
  server:
    links:
      - rabbitmq
    build:
      context: .
    command: ["python3", "-um", "japronto", "run.app"]
    ports:
      - 8081:8080