version: '2'
services:
  # rabbitmq:
  #   image: rabbitmq:management-alpine
  #   ports:
  #     - 15672:15672
  redis:
    image: eqalpha/keydb:x86_64_v5.0.1
    ports:
      - 6379:6379
    entrypoint: keydb-server
    command: ["/etc/keydb/redis.conf", "--port", "6379"]
  dramatiq:
    links:
      # - rabbitmq
      - redis
    build:
      context: .
    env_file:
      - .env
    volumes:
      - /tmp/dramatiq-prometheus
    command: ["dramatiq", "tasks"]
  # cron:
  #   links:
  #     - rabbitmq
  #     - redis
  #   build:
  #     context: .
  #   env_file:
  #     - .env
  #   command: ["python3", "-u", "cron_gitlab_sync_avatars_prepare.py"]
  server:
    links:
      # - rabbitmq
      - redis
    build:
      context: .
    volumes:
      - ./:/src
    command: ["python3", "-um", "japronto", "run.app"]
    env_file:
      - .env
    ports:
      - 8081:8080
